-module(myArbiter_tests).
-include_lib("eunit/include/eunit.hrl").

move_test_() ->
    myArbiter:start(myLists:getState1()),
    arbiter ! {arbiterRequest,self(),action,[move,{1,1},{0,1}]},
    receive OutMap1 -> OutMap1 end,
    arbiter ! {arbiterRequest,self(),action,[move,{1,1},{1,0}]},
    receive OutMap2 -> OutMap2 end,
    arbiter ! {arbiterRequest,self(),action,[move,{9,9},{10,9}]},
    receive OutMap3 -> OutMap3 end,
    arbiter ! {arbiterRequest,self(),action,[move,{9,9},{9,10}]},
    receive OutMap4 -> OutMap4 end,
    arbiter ! {arbiterRequest,self(),action,[move,{1,1},{1,2}]},
    receive Ok -> Ok end,
    arbiter ! {arbiterRequest,self(),action,[move,{5,1},{1,2}]},
    receive TooFar -> TooFar end,
    arbiter ! {arbiterRequest,self(),action,[move,{1,2},{1,3}]},
    receive Block -> Block end,
    arbiter ! {arbiterRequest,self(),action,[move,{1,2},{1,5}]},
    receive TooFar2 -> TooFar2 end,
    arbiter ! {arbiterRequest,self(),action,[move,{9,9},{8,8}]},
    receive Ok2 -> Ok2 end,
    arbiter ! {arbiterRequest,self(),info,[debug]},
    receive S1 -> S1 end,
    [?_assertEqual(blocked, OutMap1),
    ?_assertEqual(blocked, OutMap2),
    ?_assertEqual(blocked, OutMap3),
    ?_assertEqual(blocked, OutMap4),
    ?_assertEqual(ok, Ok),
    ?_assertEqual(invalid, TooFar),
    ?_assertEqual(blocked, Block),
    ?_assertEqual(invalid, TooFar2),
    ?_assertEqual(ok, Ok2),
    ?_assertEqual({" ",0}, myLists:get_(1,1,element(3,S1))),
    ?_assertEqual({"r",0}, myLists:get_(1,2,element(3,S1)))].

enter_test_() ->
    myArbiter:start(myLists:getState1()),
    arbiter ! {arbiterRequest,self(),action,[enter,3,foo]},
    receive NoEntry -> NoEntry end,
    arbiter ! {arbiterRequest,self(),action,[enter,1,foo]},
    receive Ok -> Ok end,
    arbiter ! {arbiterRequest,self(),action,[enter,1,foo]},
    receive Robot -> Robot end,
    arbiter ! {arbiterRequest,self(),info,[debug]},
    receive S1 -> S1 end,
    [?_assertEqual(invalid, NoEntry),
    ?_assertEqual(ok, Ok),
    ?_assertEqual(blocked, Robot),
    ?_assertEqual({"r",0}, myLists:get_(3,3,element(3,S1)))].
